from . import trucking_route
from . import trucking_border
from . import trucking_vehicle
from . import account_payment
from . import trucking_load
from . import trucking_load_border
from . import res_partner
from . import account_move
from . import account_payment_register
from . import trucking_trailer
